### ISSUE TITLE
Hello! Is that really work?

### ISSUE THREAD

**Issue by gaorunzebit** [MihaiLupoiu/AMPI#1]
Dear author:

Hello! I am learning and trying to rewrite the tiled QR algorithm. However, I can't make it work. The results I got always were worng. Is this C code really work? I notice this C code may be not completed. For example, some important parts of tiled QR algorithm are in annotation... 

Thank you. Looking forward to communicating with you.

**Comment by MihaiLupoiu** [comment]
Hi!

This project was as part of my mastres degree. It worked in it's moment but unfortunetly now I don't remember the details. I know what we used a special matematical library (lapack and blas) for making the mathematical operations. 

The important part of tiled QR you are mentioning are sudocode of the algorithm. But the functions are used as for example [here](https://github.com/MihaiLupoiu/AMPI/blob/master/AMPI/C/qr.c#L80).

Let me know if it helps. 😄

**Comment by gaorunzebit** [comment]
Thank you! Sir.

Glad to hear that this project has ever worked. I was doubted whether it real can work. Unluckly, I haven't solve this problem up to now. So I change my plan and don't use this algorithm... 7_7

Whatever. Many thanks to you.

**Comment by MihaiLupoiu** [comment]
Sorry to hear that. Best of luck with your problem!

Closing the issue.
